apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-config
data:
  config.js: |
    window.env = {
        API_URL: "http://a70c9e322b2324cf287c974af6a9c745-1534476975.eu-north-1.elb.amazonaws.com/api/v1"
    };
